{% set version = "1.6.2" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf4-python/archive/v{{version}}rel.tar.gz
  sha256: f216defd771a6bc143d99d060793813b7e29d6907455127301ab8983592b780c

build:
  number: 0
  skip: True  # [s390x]
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4
  ignore_run_exports:
    - hdf5

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - cftime
    - hdf5
    - libnetcdf
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cftime
    - hdf5
    - {{ pin_compatible('libnetcdf', min_pin='x.x', max_pin='x.x') }}

test:
  imports:
    - netCDF4
    - cftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h

about:
  home: https://unidata.github.io/netcdf4-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: netcdf4-python is a Python interface to the netCDF C library.
  description: |
    netCDF version 4 has many features not found in earlier versions of the library and is 
    implemented on top of HDF5. This module can read and write files in both the new netCDF 4 
    and the old netCDF 3 format, and can create files that are readable by HDF5 clients. 
    The API modelled after Scientific.IO.NetCDF, and should be familiar to users of that module.
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
