{% set name = "netcdf4" %}
{% set version = "1.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Unidata/{{ name }}-python/archive/v{{version}}rel.tar.gz
  sha256: cce7d42a83f84b6ce6288bb2fb171d5ffd294f1a1ba2650807d238ae961e9629
  patches:  # [win]
    - patches/00_fix_win_test.patch  # [win]

build:
  number: 2
  skip: True  # [py<38]
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4
  ignore_run_exports:
    - hdf5

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython >=0.29
    - hdf5  {{ hdf5 }}
    - libnetcdf {{ libnetcdf }}
    - setuptools >=61
    - setuptools-scm >=3.4
    - toml
    - wheel
  run:
    - python
    - numpy
    - cftime
    - certifi
    - hdf5
    - {{ pin_compatible('libnetcdf', min_pin='x.x', max_pin='x.x') }}

test:
  source_files:
    - test
  imports:
    - netCDF4
    - cftime
  requires:
    - cython
    - pip
    - packaging
  commands:
    - pip check
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h
    - cd test && python run_all.py

about:
  home: https://unidata.github.io/netcdf4-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: netcdf4-python is a Python interface to the netCDF C library.
  description: |
    netCDF version 4 has many features not found in earlier versions of the library and is 
    implemented on top of HDF5. This module can read and write files in both the new netCDF 4 
    and the old netCDF 3 format, and can create files that are readable by HDF5 clients. 
    The API modelled after Scientific.IO.NetCDF, and should be familiar to users of that module.
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
