{% set version = "1.5.7" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf4-python/archive/v{{version}}rel.tar.gz
  sha256: 5673896d1d39d591423abbd4856270cc901b88bdbeaf4ab293bfd7cfd77fe8d5

build:
  number: 0
  # trigger: 1
  skip: True  # [s390x]
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4
  ignore_run_exports:
    - hdf5

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.19
    - cftime
    - hdf5
    - libnetcdf
    - setuptools >=18.0
    - wheel
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cftime
    - hdf5
    - libnetcdf

test:
  imports:
    - netCDF4
    - cftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h

about:
  home: http://unidata.github.io/netcdf4-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Provides an object-oriented python interface to the netCDF version 4 library.'
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
