travis:
  secure:
    BINSTAR_TOKEN: k159DG8FFRefUb8gRkRUBAQwDI5LbKQ9aaBCPkz2HWSmCbzkwiOGh6hBpAVzmnHYKcz6BS08IH+9OWwEkhrUccZU6t4HyA7Tw1kJ6fNB3Ca/ZvtKdjSvHRnNX8mVQSJUX7Cmov3A4oFXshc2JEjlz/uhdP0KqTqtWC+mMaXT2N1Sfb1KenF3Bhs4a8x27QFkVK5UeUv1kxJxY1nUBA5EVOXOEu92xsrEhqwhQsHy0vsKMRaEaT+AB7WWRwzEDkRCoXJAM65pNmayXthpOD7WFCdRNtK0z+2BYijAq7iTC70mvfnUQexqo1pG0SnGz9bRUfKUC0NxNzRQIqWPi2Lt036R0PtdX1TX4r/uoho7St8lm37xr1W0MKmAntW1J+rC00acrm0N3gBCqNz0u8Oa0sEd97NPnazEevv/Jd7swOXHLgGtt/6GCd9PjfxVBS5r/XCdbvhtXnBiQf0oNses0CIg9f4VyOAer5R7FpcdwicUIUMz+g1u2sZ9EtA0RuH59vV1iTLxb2WOUJ+xNjYP/JPFBAIAsXDOqdhXzBymf7CPEtgmelK1RcoEQQfEJvJ2F7s/qr7JGCSTNuMvYvD1ucxC5iQS7Pb5U76NZFvwCzxRp/8SaFo0gp1vO8InHn3d96pWJeayp1oCh11mBgehtuD/GYhJE8QoBiXQSanl+24=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
